# 应用名称
spring:
  application:
    # 应用名称
    name: marketweb
  datasource:
    # 数据库用户名&密码：
    username: root
    password: 123456
    # 数据库连接地址
    # 本地  root 123456
    # url: jdbc:mysql://127.0.0.1:3306/market?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    # 服务器
    url: jdbc:mysql://121.4.175.242:3306/market?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
# 默认端口号
server:
  # 应用服务 WEB 访问端口
  port: 8081
  servlet:
    contextPath: /potato-web-market

###################################### MyBatis 配置######################################
mybatis:
  # 指定 mapper.xml 的位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
  type-aliases-package: com.potato.marketweb.bean
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true

##日志级别
logging:
  level:
    com:
      potato:
        marketweb: trace
  file:
#    #使用相对路径的方式设置日志输出的位置（项目根目录目录\my-log\mylog\spring.log）
#    path: my-log/myLog
    #绝对路径方式将日志文件输出到 【项目所在磁盘根目录\springboot\logging\my\spring.log】
    path: /logs/potato-web-market
  pattern:
    #控制台日志输出格式
    console: "%d{yyyy-MM-dd hh:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    #日志文件输出格式
    file: "%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} === - %msg%n"


